#!/bin/bash
# Zivpn Central Bot Manager
# Repo: https://github.com/Pujianto1219/ZivCilz

BOT_FILE="/etc/zivpn/bot_data"
DOMAIN=$(cat /etc/zivpn/domain 2>/dev/null || echo "VPS-Unknown")
DATE=$(date +"%Y-%m-%d %H:%M")

# Fungsi Kirim Pesan
send_msg() {
    if [ -f "$BOT_FILE" ]; then
        DATA=$(cat $BOT_FILE)
        TOKEN=$(echo $DATA | cut -d: -f1)
        ID=$(echo $DATA | cut -d: -f2)
        MSG="$1"
        curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" \
            -d chat_id="$ID" \
            -d text="$MSG" \
            -d parse_mode="Markdown" > /dev/null
    fi
}

# Fungsi Kirim File (Untuk Backup)
send_doc() {
    if [ -f "$BOT_FILE" ]; then
        DATA=$(cat $BOT_FILE)
        TOKEN=$(echo $DATA | cut -d: -f1)
        ID=$(echo $DATA | cut -d: -f2)
        FILE="$1"
        CAPTION="$2"
        curl -s -F chat_id="$ID" \
             -F document=@"$FILE" \
             -F caption="$CAPTION" \
             -F parse_mode="Markdown" \
             "https://api.telegram.org/bot$TOKEN/sendDocument" > /dev/null
    fi
}

# === LOGIKA UTAMA ===
case $1 in
    setup)
        # Menu Setup Interaktif
        clear
        echo "=== TELEGRAM BOT SETUP ==="
        read -p "Masukkan Bot Token : " token
        read -p "Masukkan Chat ID   : " chatid
        if [[ -n "$token" && -n "$chatid" ]]; then
            echo "${token}:${chatid}" > $BOT_FILE
            echo "Data tersimpan!"
            # Test
            bash "$0" test
        else
            echo "Data tidak valid."
        fi
        ;;
        
    test)
        send_msg "✅ *ZIVPN BOT TEST*%0A%0AHalo, Bot berhasil terhubung ke VPS: \`$DOMAIN\`"
        echo "Pesan test dikirim."
        ;;
        
    create)
        # Usage: zivbot create <user> <exp_date>
        USER=$2
        EXP=$3
        MSG="✨ *CREATED USER ZIVPN*%0A%0A👤 User: \`$USER\`%0A📅 Expired: \`$EXP\`%0A🖥️ Domain: \`$DOMAIN\`%0A%0A_Generated by ZivCilz_"
        send_msg "$MSG"
        ;;
        
    delete)
        # Usage: zivbot delete <user>
        USER=$2
        MSG="🗑️ *DELETED USER ZIVPN*%0A%0A👤 User: \`$USER\`%0A❌ Status: Deleted by Admin%0A%0A_System Notification_"
        send_msg "$MSG"
        ;;
        
    renew)
        # Usage: zivbot renew <user> <new_exp>
        USER=$2
        EXP=$3
        MSG="🔄 *RENEW USER ZIVPN*%0A%0A👤 User: \`$USER\`%0A📅 New Expired: \`$EXP\`%0A%0A_System Notification_"
        send_msg "$MSG"
        ;;
        
    expired)
        # Usage: zivbot expired <user>
        USER=$2
        MSG="⚠️ *USER EXPIRED*%0A%0A👤 User: \`$USER\`%0A❌ Status: Deleted by Auto-XP%0A%0A_System Notification_"
        send_msg "$MSG"
        ;;
        
    backup)
        # Usage: zivbot backup <filepath>
        FILE=$2
        CAPTION="📦 *BACKUP DATA VPS*%0A%0A🖥️ Domain: \`$DOMAIN\`%0A📅 Tanggal: \`$DATE\`%0A%0A_Auto Backup System_"
        send_doc "$FILE" "$CAPTION"
        ;;

    limit)
        # Usage: zivbot limit <user> <ip_count>
        USER=$2
        COUNT=$3
        MSG="🚫 *USER LIMIT REACHED*%0A%0A👤 User: \`$USER\`%0A🔢 Login: \`$COUNT\` IP%0A❌ Tindakan: Multi-Login Kill%0A%0A_Security System_"
        send_msg "$MSG"
        ;;
        
    *)
        # Jika dijalankan tanpa argumen, masuk ke mode setup
        if [ -z "$1" ]; then
            bash "$0" setup
        else
            echo "Command tidak dikenal."
        fi
        ;;
esac
